import type { DocSection, ReportDoc } from '../reports/report-doc';
import type { SupportedLocale } from '../translation/translation.types';
import type { NcnpOrgSummaryRow, NcnpReport } from './ncnp-report.types';
import {
  AGE_BRACKET_LABELS,
  AGE_BRACKET_LABELS_AR,
  AGE_BRACKET_ORDER,
  GENDER_LABELS,
  GENDER_LABELS_AR,
  NEED_SOURCE_LABELS,
  NEED_SOURCE_LABELS_AR,
  REJECTION_REASON_LABELS,
  REJECTION_REASON_LABELS_AR,
  localizedLabel,
} from './ncnp-report-labels';

/**
 * Fixed report vocabulary for this document — section headings, column
 * names, and the fixed English sentences the report prints when a section
 * has no data. Every Arabic value here is copied verbatim from the same
 * client-approved catalogue the in-app NCNP report viewer already reads
 * (Project-RIO-Frontend/messages/ar.json, under systemAdmin.ncnpReport.* /
 * app.reports.content.*) — this export must say exactly what the screen
 * already says, never a second, independently-worded Arabic string for the
 * same heading.
 *
 * What does NOT belong here: anything a user typed or an AI wrote (Need
 * titles, organization names, region/domain names, ...) — those flow
 * through as-is; the frontend's own AutoTranslate/localizedText already
 * covers that content in the in-app view, and this export is a snapshot of
 * whatever the underlying record says.
 */
const LABELS_AR: Record<string, string> = {
  Active: 'نشطة',
  'Age Distribution': 'التوزيع العمري',
  Archived: 'مؤرشفة',
  'Avg / Survey': 'المتوسط / استبيان',
  'Data Quality Notes': 'ملاحظات جودة البيانات',
  Domain: 'المجال',
  'Dormant Threshold': 'عتبة الخمول',
  Draft: 'مسودة',
  'Duplicate-Flagged Responses': 'استجابات معلَّمة كمكررة',
  'Equity Flag': 'علم الإنصاف',
  Evidence: 'الأدلة',
  'Gender Distribution': 'التوزيع حسب الجنس',
  'Generated At': 'تاريخ الإنشاء',
  'Generated By': 'أُنشئ بواسطة',
  'Generated On': 'تاريخ الإنشاء',
  'Highest-Priority Villages': 'أعلى القرى ذات الأولوية',
  Inactive: 'غير نشطة',
  Indicator: 'المؤشر',
  'Low-Confidence Responses': 'الردود منخفضة الثقة',
  'NCNP Compiled Report': 'التقرير المجمّع لـ إن سي إن بي',
  Need: 'الحاجة',
  Needs: 'الاحتياجات',
  'Needs Not Yet Classified': 'احتياجات لم تُصنَّف بعد',
  'Needs With Evidence': 'احتياجات لديها أدلة',
  'Needs Without Evidence': 'احتياجات بدون أدلة',
  'Needs by Center': 'الاحتياجات حسب المركز',
  'Needs by Governorate': 'الاحتياجات حسب المحافظة',
  'Needs by Region': 'الاحتياجات حسب المنطقة',
  'Needs by Sub-Domain': 'الاحتياجات حسب المجال الفرعي',
  'No Needs have a village-priority assessment yet.': 'لا توجد احتياجات لديها تقييم أولوية على مستوى القرية بعد.',
  'No age-bracket data available for this period yet.': 'لا توجد بيانات فئات عمرية متاحة لهذه الفترة بعد.',
  'No recorded activity': 'لا يوجد نشاط مسجَّل',
  'No rejected surveys recorded for this period yet.': 'لم يتم تسجيل استبيانات مرفوضة لهذه الفترة بعد.',
  Organization: 'الكيان',
  'Organization Health': 'سلامة الكيان',
  Organizations: 'الكيانات',
  'Organizations Needing Attention': 'كيانات تحتاج اهتمامًا',
  'Organizations by Center': 'الكيانات حسب المركز',
  'Organizations by Governorate': 'الكيانات حسب المحافظة',
  'Organizations by Region': 'الكيانات حسب المنطقة',
  'Organizations with the Highest Number of Studies': 'الكيانات ذات أعلى عدد من الدراسات',
  'Primary Gap': 'الفجوة الرئيسية',
  'Priority Needs': 'الاحتياجات ذات الأولوية',
  'Priority Score': 'درجة الأولوية',
  Published: 'منشور',
  Region: 'المنطقة',
  Rejected: 'مرفوض',
  'Rejection Reason Breakdown': 'تفصيل أسباب الرفض',
  'Reporting Period': 'فترة التقرير',
  Responses: 'الردود',
  'Responses Quality-Assessed': 'استجابات جرى تقييم جودتها',
  'Responses by Region': 'الاستجابات حسب المنطقة',
  Source: 'المصدر',
  'Source Ref': 'مرجع المصدر',
  Status: 'الحالة',
  Studies: 'الدراسات',
  'Studies by Region': 'الدراسات حسب المنطقة',
  'Study Status': 'حالة الدراسة',
  Submitted: 'مُرسلة',
  Surveys: 'الاستبيانات',
  'Top Critical Needs': 'أهم الاحتياجات الحرجة',
  'Total Needs': 'إجمالي الاحتياجات',
  Village: 'القرية',
  'Village Priority Classification': 'تصنيف أولوية القرى',
  Yes: 'نعم',
  No: 'لا',
};

/** Looks up a fixed report string in `LABELS_AR` for Arabic; English (the
 *  literal passed in) otherwise or if a given string has no Arabic entry
 *  yet — same never-drop-the-row fallback the enum label maps use. */
function t(text: string, locale: SupportedLocale): string {
  if (locale !== 'ar') return text;
  return LABELS_AR[text] ?? text;
}

function fmtDate(iso: string, locale: SupportedLocale): string {
  const d = new Date(iso);
  return locale === 'ar'
    ? d.toLocaleString('ar-SA-u-nu-latn', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    : d.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function pct(stat: { current: number; previous: number; changePct: number | null }, locale: SupportedLocale): string {
  if (stat.changePct === null) return locale === 'ar' ? `${stat.current} (جديد)` : `${stat.current} (new)`;
  const sign = stat.changePct > 0 ? '+' : '';
  return locale === 'ar'
    ? `${stat.current} (${sign}${stat.changePct.toFixed(1)}٪ مقارنة بالفترة السابقة)`
    : `${stat.current} (${sign}${stat.changePct.toFixed(1)}% vs. prior period)`;
}

// Maps the live NcnpReport payload into the same render-agnostic ReportDoc
// model every other report export already uses (see report-doc.ts) — reuses
// the existing renderReportPdf/renderReportExcel renderers unchanged rather
// than building a second PDF/Excel pipeline for one report type.
export function buildNcnpReportDoc(
  report: NcnpReport,
  generatedByName: string,
  auditRows?: Array<{ label: string; value: string }>,
  locale: SupportedLocale = 'en',
): ReportDoc {
  const {
    summary,
    orgHealth,
    orgSummary,
    needDomains,
    needSubDomains,
    needsGeography,
    studyStatus,
    studyOverview,
    geography,
    surveyAnalytics,
    surveyGeography,
    regionSummary,
    responseAnalytics,
    priorityOverview,
    criticalNeeds,
    dataQualityNotes,
    domainRegionIntersections,
  } = report;

  const sections: DocSection[] = [
    {
      kind: 'keyvalue',
      heading: t('Platform Summary', locale),
      rows: [
        { label: t('Organizations', locale), value: pct({ ...summary.newThisPeriod.organizations, current: summary.totals.organizations }, locale) },
        { label: t('Studies', locale), value: pct({ ...summary.newThisPeriod.studies, current: summary.totals.studies }, locale) },
        { label: t('Surveys', locale), value: pct({ ...summary.newThisPeriod.surveys, current: summary.totals.surveys }, locale) },
        { label: t('Responses', locale), value: pct({ ...summary.newThisPeriod.responses, current: summary.totals.responses }, locale) },
        { label: t('Total Needs', locale), value: String(summary.totals.needs) },
      ],
    },
    criticalNeeds.topCriticalNeeds.length === 0
      ? { kind: 'note', heading: t('Top Critical Needs', locale), text: t('No Needs have a village-priority assessment yet — nothing to rank.', locale) }
      : {
          kind: 'list',
          heading: t('Top Critical Needs', locale),
          items: criticalNeeds.topCriticalNeeds.map(
            (n) => `${n.needTitle} (${n.organizationName} — ${n.domain ?? t('Unclassified', locale)}) — ${n.priorityStatus}, score ${n.priorityScore.toFixed(1)}`,
          ),
        },
    {
      kind: 'keyvalue',
      heading: t('Organization Health', locale),
      rows: [
        { label: t('Active', locale), value: String(orgHealth.active) },
        { label: t('Inactive', locale), value: String(orgHealth.inactive) },
        { label: `${locale === 'ar' ? 'خامل' : 'Dormant'} (${orgHealth.dormantDays}+ ${locale === 'ar' ? 'يومًا من الخمول' : 'days inactive'})`, value: String(orgHealth.dormant) },
      ],
    },
  ];

  if (orgHealth.needsAttention.length > 0) {
    sections.push({
      kind: 'table',
      heading: t('Organizations Needing Attention', locale),
      columns: [t('Organization', locale), t('Last Activity', locale)],
      rows: orgHealth.needsAttention.map((o) => [o.organizationName, o.lastActivity ? fmtDate(o.lastActivity, locale) : t('No recorded activity', locale)]),
    });
  }

  const orgSummaryLists: Array<{ rows: NcnpOrgSummaryRow[]; label: string; value: (r: NcnpOrgSummaryRow) => number }> = [
    { rows: orgSummary.byStudies, label: t('Studies', locale), value: (r) => r.studyCount },
    { rows: orgSummary.bySurveys, label: t('Surveys', locale), value: (r) => r.surveyCount },
    { rows: orgSummary.byResponses, label: t('Responses', locale), value: (r) => r.responseCount },
  ];
  for (const { rows, label, value } of orgSummaryLists) {
    sections.push({
      kind: 'table',
      heading: locale === 'ar'
        ? `أفضل الكيانات — حسب ${label} (أعلى ${rows.length} من ${orgSummary.totalOrganizations})`
        : `Top Organizations — by ${label} (top ${rows.length} of ${orgSummary.totalOrganizations})`,
      columns: [t('Organization', locale), label, t('Status', locale)],
      rows: rows.map((r) => [r.organizationName, String(value(r)), r.isActive ? t('Active', locale) : t('Inactive', locale)]),
    });
  }

  sections.push({
    kind: 'bars',
    heading: locale === 'ar' ? 'فئات الاحتياجات — حسب المجال' : 'Need Categories — by Domain',
    max: Math.max(1, ...needDomains.map((d) => d.needCount)),
    bars: needDomains.map((d) => ({ label: d.domainName, value: d.needCount })),
  });

  sections.push({
    kind: 'bars',
    heading: t('Needs by Sub-Domain', locale),
    max: Math.max(1, ...needSubDomains.map((d) => d.needCount)),
    bars: needSubDomains.map((d) => ({ label: `${d.domainName} — ${d.subDomainName}`, value: d.needCount })),
  });

  // Kingdom-wide rollup of Needs themselves — distinct from the
  // Organizations-by-Region/Governorate/Center breakdown below, which
  // counts organizations, not individual Needs.
  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'bars',
        heading: t('Needs by Region', locale),
        max: Math.max(1, ...needsGeography.byRegion.map((g) => g.count)),
        bars: needsGeography.byRegion.map((g) => ({ label: g.name, value: g.count })),
      },
      {
        kind: 'bars',
        heading: t('Needs by Governorate', locale),
        max: Math.max(1, ...needsGeography.byGovernorate.map((g) => g.count)),
        bars: needsGeography.byGovernorate.map((g) => ({ label: g.name, value: g.count })),
      },
    ],
  });

  sections.push({
    kind: 'bars',
    heading: t('Needs by Center', locale),
    max: Math.max(1, ...needsGeography.byCenter.map((g) => g.count)),
    bars: needsGeography.byCenter.map((g) => ({ label: g.name, value: g.count })),
  });

  if (domainRegionIntersections.length > 0) {
    sections.push({
      kind: 'table',
      heading: locale === 'ar' ? 'تحليل الأنماط والتقاطعات — المنطقة × المجال' : 'Pattern & Intersection Analysis — Region x Domain',
      columns: [t('Region', locale), t('Domain', locale), t('Needs', locale)],
      rows: domainRegionIntersections.map((c) => [c.regionName, c.domainName, String(c.needCount)]),
    });
  }

  sections.push({
    kind: 'pie',
    heading: t('Study Status', locale),
    slices: [
      { label: t('Active', locale), value: studyStatus.active },
      { label: t('Archived', locale), value: studyStatus.archived },
    ],
  });

  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'bars',
        heading: t('Organizations by Region', locale),
        max: Math.max(1, ...geography.organizationsByRegion.map((g) => g.count)),
        bars: geography.organizationsByRegion.map((g) => ({ label: g.name, value: g.count })),
      },
      {
        kind: 'bars',
        heading: t('Studies by Region', locale),
        max: Math.max(1, ...geography.studiesByRegion.map((g) => g.count)),
        bars: geography.studiesByRegion.map((g) => ({ label: g.name, value: g.count })),
      },
    ],
  });

  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'bars',
        heading: t('Organizations by Governorate', locale),
        max: Math.max(1, ...geography.organizationsByGovernorate.map((g) => g.count)),
        bars: geography.organizationsByGovernorate.map((g) => ({ label: g.name, value: g.count })),
      },
      {
        kind: 'bars',
        heading: t('Organizations by Center', locale),
        max: Math.max(1, ...geography.organizationsByCenter.map((g) => g.count)),
        bars: geography.organizationsByCenter.map((g) => ({ label: g.name, value: g.count })),
      },
    ],
  });

  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'table',
        heading: t('Organizations with the Highest Number of Studies', locale),
        columns: [t('Organization', locale), t('Studies', locale)],
        rows: studyOverview.topOrgsByStudyCount.map((o) => [o.organizationName, String(o.studyCount)]),
      },
      {
        kind: 'bars',
        heading: locale === 'ar' ? 'الدراسات المنشأة — آخر 12 شهرًا' : 'Studies Created — Last 12 Months',
        max: Math.max(1, ...studyOverview.studiesCreatedTrend.map((p) => p.count)),
        bars: studyOverview.studiesCreatedTrend.map((p) => ({ label: p.month, value: p.count })),
      },
    ],
  });

  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'bars',
        heading: t('Surveys by Governorate', locale),
        max: Math.max(1, ...surveyGeography.byGovernorate.map((g) => g.count)),
        bars: surveyGeography.byGovernorate.map((g) => ({ label: g.name, value: g.count })),
      },
      {
        kind: 'bars',
        heading: t('Surveys by Center', locale),
        max: Math.max(1, ...surveyGeography.byCenter.map((g) => g.count)),
        bars: surveyGeography.byCenter.map((g) => ({ label: g.name, value: g.count })),
      },
    ],
  });

  if (regionSummary.length > 0) {
    sections.push({
      kind: 'table',
      heading: locale === 'ar' ? 'حسب المنطقة — ملخص' : 'By Region — Summary',
      columns: [t('Region', locale), t('Surveys', locale), t('Responses', locale), t('Avg / Survey', locale)],
      rows: regionSummary.map((r) => [r.regionName, String(r.surveyCount), String(r.responseCount), r.avgResponsesPerSurvey.toFixed(1)]),
    });
  }

  sections.push({
    kind: 'pie',
    heading: locale === 'ar' ? 'حالة اعتماد الاستبيانات — على مستوى المنصة' : 'Survey Approval Status — Platform-Wide',
    slices: [
      { label: t('Draft', locale), value: surveyAnalytics.statusPlatformWide.draft },
      { label: t('Submitted', locale), value: surveyAnalytics.statusPlatformWide.submitted },
      { label: t('Published', locale), value: surveyAnalytics.statusPlatformWide.published },
      { label: t('Rejected', locale), value: surveyAnalytics.statusPlatformWide.rejected },
    ],
  });

  sections.push({
    kind: 'note',
    heading: locale === 'ar' ? 'متوسط حصيلة الاستجابات' : 'Average Response Yield',
    text: locale === 'ar'
      ? `${surveyAnalytics.avgResponsesPerPublishedSurvey.toFixed(1)} متوسط الاستجابات لكل استبيان منشور، على مستوى المنصة.`
      : `${surveyAnalytics.avgResponsesPerPublishedSurvey.toFixed(1)} average responses per published survey, platform-wide.`,
  });

  // Counts historical rejection events (see NcnpReportService), not
  // surveys currently sitting at REJECTED — check the breakdown itself,
  // not statusPlatformWide.rejected, so a rejected-then-corrected-then-
  // published survey still shows its rejection history here.
  if (surveyAnalytics.rejectionReasonBreakdown.length === 0) {
    sections.push({
      kind: 'note',
      heading: t('Rejection Reason Breakdown', locale),
      text: t('No rejected surveys recorded for this period yet.', locale),
    });
  } else {
    sections.push({
      kind: 'bars',
      heading: t('Rejection Reason Breakdown', locale),
      max: Math.max(1, ...surveyAnalytics.rejectionReasonBreakdown.map((r) => r.count)),
      bars: surveyAnalytics.rejectionReasonBreakdown.map((r) => ({
        label: `${r.reasonCode} — ${localizedLabel(REJECTION_REASON_LABELS, REJECTION_REASON_LABELS_AR, r.reasonCode, locale)}`,
        value: r.count,
      })),
    });
  }

  if (surveyAnalytics.statusByRegion.length > 0) {
    sections.push({
      kind: 'table',
      heading: locale === 'ar' ? 'حالة اعتماد الاستبيانات — حسب المنطقة' : 'Survey Approval Status — by Region',
      columns: [t('Region', locale), t('Draft', locale), t('Submitted', locale), t('Published', locale), t('Rejected', locale)],
      rows: surveyAnalytics.statusByRegion.map((r) => [
        r.regionName,
        String(r.status.draft),
        String(r.status.submitted),
        String(r.status.published),
        String(r.status.rejected),
      ]),
    });
  }

  sections.push({
    kind: 'bars',
    heading: t('Responses by Region', locale),
    max: Math.max(1, ...responseAnalytics.responsesByRegion.map((r) => r.count)),
    bars: responseAnalytics.responsesByRegion.map((r) => ({ label: r.regionName, value: r.count })),
  });

  sections.push({
    kind: 'pie',
    heading: t('Gender Distribution', locale),
    slices: responseAnalytics.genderDistribution.map((g) => ({
      label: localizedLabel(GENDER_LABELS, GENDER_LABELS_AR, g.gender, locale),
      value: g.count,
    })),
  });

  const ageTotal = responseAnalytics.ageBracketDistribution.reduce((sum, a) => sum + a.count, 0);
  if (ageTotal === 0) {
    sections.push({
      kind: 'note',
      heading: t('Age Distribution', locale),
      text: t('No age-bracket data available for this period yet.', locale),
    });
  } else {
    const ageCountByBracket = new Map(responseAnalytics.ageBracketDistribution.map((a) => [a.ageBracket, a.count]));
    sections.push({
      kind: 'pie',
      heading: t('Age Distribution', locale),
      slices: AGE_BRACKET_ORDER.filter((key) => (ageCountByBracket.get(key) ?? 0) > 0).map((key) => ({
        label: localizedLabel(AGE_BRACKET_LABELS, AGE_BRACKET_LABELS_AR, key, locale),
        value: ageCountByBracket.get(key) ?? 0,
      })),
    });
  }
  if (responseAnalytics.hasResponsesWithoutAgeBracket) {
    sections.push({
      kind: 'note',
      heading: locale === 'ar' ? 'التوزيع العمري — ملاحظة' : 'Age Distribution — Note',
      text: locale === 'ar'
        ? 'البيانات الديموغرافية العمرية متاحة فقط للاستجابات التي جُمعت بعد تاريخ إطلاق هذه الميزة.'
        : 'Age demographics are available only for responses collected after the feature go-live date.',
    });
  }

  sections.push({
    kind: 'columns',
    children: [
      {
        kind: 'bars',
        heading: locale === 'ar' ? 'أفضل الكيانات — حسب إجمالي الاستجابات' : 'Top Organizations — by Total Responses',
        max: Math.max(1, ...responseAnalytics.topOrgsByTotalResponses.map((o) => o.value)),
        bars: responseAnalytics.topOrgsByTotalResponses.map((o) => ({ label: o.organizationName, value: o.value })),
      },
      {
        kind: 'bars',
        heading: locale === 'ar' ? 'أفضل الكيانات — حسب متوسط الاستجابات / استبيان' : 'Top Organizations — by Avg. Responses / Survey',
        max: Math.max(1, ...responseAnalytics.topOrgsByAvgResponsesPerSurvey.map((o) => o.value)),
        bars: responseAnalytics.topOrgsByAvgResponsesPerSurvey.map((o) => ({
          label: o.organizationName,
          value: Math.round(o.value * 10) / 10,
        })),
      },
    ],
  });

  sections.push({
    kind: 'pie',
    heading: t('Village Priority Classification', locale),
    slices: priorityOverview.byStatus.map((s) => ({ label: s.status, value: s.count })),
  });

  sections.push({
    kind: 'bars',
    heading: locale === 'ar' ? 'مقارنة المجالات — متوسط درجة الأداء' : 'Domain Comparison — Avg. Performance Score',
    max: 100,
    bars: priorityOverview.domainComparison.map((d) => ({ label: d.domainName, value: Math.round(d.avgPerformanceScore) })),
  });

  if (priorityOverview.topPriorityVillages.length > 0) {
    sections.push({
      kind: 'table',
      heading: t('Highest-Priority Villages', locale),
      columns: [t('Village', locale), t('Priority Score', locale), t('Status', locale)],
      rows: priorityOverview.topPriorityVillages.map((v) => [v.villageId, v.priorityScore.toFixed(1), v.priorityStatus]),
    });
  }

  // Need-level (not village-level) — score/evidence/gap/source per Need,
  // ranked most critical first (see NcnpReportService.buildCriticalNeeds).
  if (criticalNeeds.priorityNeeds.length === 0) {
    sections.push({ kind: 'note', heading: t('Priority Needs', locale), text: t('No Needs have a village-priority assessment yet.', locale) });
  } else {
    sections.push({
      kind: 'table',
      heading: locale === 'ar'
        ? `الاحتياجات ذات الأولوية (أعلى ${criticalNeeds.priorityNeeds.length} من ${criticalNeeds.totalRankableNeeds} قابلة للترتيب)`
        : `Priority Needs (top ${criticalNeeds.priorityNeeds.length} of ${criticalNeeds.totalRankableNeeds} rankable)`,
      // Excel has no page-width constraint the way the PDF does, so this
      // carries the full Unified Need Record field set — Indicator, Region
      // (unit_geo), and Source Ref included, unlike the PDF's leaner table.
      columns: [
        t('Need', locale),
        t('Domain', locale),
        locale === 'ar' ? 'الدرجة' : 'Score',
        t('Status', locale),
        t('Equity Flag', locale),
        t('Primary Gap', locale),
        t('Indicator', locale),
        t('Region', locale),
        t('Evidence', locale),
        t('Source', locale),
        t('Source Ref', locale),
      ],
      rows: criticalNeeds.priorityNeeds.map((n) => [
        n.needTitle,
        n.domain ?? t('Unclassified', locale),
        n.priorityScore.toFixed(1),
        n.priorityStatus,
        n.equityFlag ? t('Yes', locale) : t('No', locale),
        n.primaryGap ?? '—',
        n.indicatorId ?? '—',
        n.unitGeoRegion ?? '—',
        String(n.evidenceCount),
        localizedLabel(NEED_SOURCE_LABELS, NEED_SOURCE_LABELS_AR, n.source, locale),
        n.sourceRef ?? '—',
      ]),
    });
  }

  // Mandatory — present even when every count is zero, never omitted just
  // because nothing has happened yet (e.g. no quality assessments run).
  sections.push({
    kind: 'keyvalue',
    heading: t('Data Quality Notes', locale),
    rows: [
      { label: t('Responses Quality-Assessed', locale), value: `${dataQualityNotes.assessedResponses} / ${dataQualityNotes.totalResponses}` },
      { label: t('Low-Confidence Responses', locale), value: String(dataQualityNotes.lowConfidenceCount) },
      { label: t('Duplicate-Flagged Responses', locale), value: String(dataQualityNotes.duplicateFlaggedCount) },
      { label: t('Needs With Evidence', locale), value: `${dataQualityNotes.needsWithEvidence} of ${dataQualityNotes.totalNeeds}` },
      { label: t('Needs Without Evidence', locale), value: String(dataQualityNotes.needsWithoutEvidence) },
      { label: t('Needs Not Yet Classified', locale), value: String(dataQualityNotes.needsUnclassified) },
    ],
  });

  return {
    title: t('NCNP Compiled Report', locale),
    headerBand: [
      { label: t('Reporting Period', locale), value: locale === 'ar' ? `آخر ${summary.newThisPeriod.periodDays} يومًا` : `Last ${summary.newThisPeriod.periodDays} days` },
      { label: t('Dormant Threshold', locale), value: locale === 'ar' ? `${orgHealth.dormantDays}+ يومًا من الخمول` : `${orgHealth.dormantDays}+ days inactive` },
      { label: t('Generated On', locale), value: fmtDate(report.generatedAt, locale) },
      { label: t('Generated By', locale), value: generatedByName },
    ],
    sections,
    audit: auditRows ?? [{ label: t('Generated At', locale), value: fmtDate(report.generatedAt, locale) }],
  };
}
