import { describe, expect, it } from "vitest";
import { buildReportDoc } from "./report-doc";
import { renderReportExcel } from "./excel-builder";
import { renderReportPdf } from "./pdf-builder";

/**
 * RPT17 Evidence Document-Based Report — export parity.
 *
 * An evidence-only report carries no severity, coverage, dashboard, domains or
 * topPriorities. buildReportDoc's `isCore` predicate tested only those keys, so
 * RPT17 failed every arm, skipped the whole core branch, and exported as a
 * single flat "Summary" blob — geography, the document register, every AI
 * summary and Response Quality were absent from the PDF and the spreadsheet
 * while the on-screen report showed them in full.
 *
 * The shape below mirrors a real generated payload. These assertions guard the
 * predicate against drifting back out of step with the viewer's own `isCore`,
 * and guard the per-document blocks that the exporter used to drop.
 */
const RPT17_CONTENT: Record<string, unknown> = {
  header: {
    studyName: "water",
    entityName: "Demo NGO",
    methodologyVersion: "v1.0 - Approved implementation baseline",
    cycleNumber: 3,
    dateTime: "2026-08-03T07:13:52.092Z",
  },
  geography: {
    region: "Northern Borders",
    governorate: "Arar, Rafha",
    center: "Al-Ajramiyah",
    regions: [{ id: "Northern Borders", name: "Northern Borders", count: 4 }],
    mapUnitLabel: ["document", "documents"],
  },
  responseQuality: {
    submittedResponses: 4,
    validResponses: 4,
    overallConfidence: "LOW",
    confidenceReason: "Small sample: 4 valid response(s), below the 10 required.",
    validResponseRatePct: 100,
    dontKnowRate: 0,
    dontKnowBand: "negligible",
  },
  evidenceSection: {
    totalDocuments: 2,
    documents: [
      {
        title: "Al Safa field visit",
        documentType: "ASSESSMENT_NOTE",
        sourceReferenceId: "REF-001",
        collectedDate: "2026-07-30",
        summaryStatus: "OFFICER_CONFIRMED",
        aiSummary: {
          evidenceNote: "Qualitative evidence; does not calculate or replace survey scores.",
          summary: "A routine visit recording water access observations.",
          keyFindings: [{ finding: "Standpipe intermittent", sourceReferenceId: "REF-001" }],
          themes: [{ theme: "Water availability", description: "Seasonal shortfall", sourceReferenceId: "REF-001" }],
          supportingStatements: [{ statement: "Water runs three days a week", sourceReferenceId: "REF-001", pageOrSection: "Section 1" }],
          risksOrConcerns: [{ concern: "Single point of failure for the village supply" }],
          documentLimitations: ["Reflects one routine visit only."],
        },
      },
      {
        title: "Community feedback log",
        documentType: "FIELD_REPORT",
        sourceReferenceId: "REF-002",
        collectedDate: "2026-07-28",
        summaryStatus: "DRAFT",
        aiSummary: {
          summary: "Informal feedback gathered from households.",
          keyFindings: [{ finding: "Collection time exceeds 30 minutes" }],
          themes: [{ theme: "Water availability", description: "Repeated across sources" }],
        },
      },
    ],
  },
  recommendations: ["Investigate year-round source availability."],
  approval: { generatedBy: "officer-1", generatedAt: "2026-08-03T07:13:52.092Z", status: "DRAFT" },
  filters: {},
  reportKind: "report",
};

const doc = buildReportDoc("water — Evidence Document Report", RPT17_CONTENT, [
  { label: "Generated by", value: "Officer" },
]);
// `columns` sections have no heading of their own, hence the `in` guard.
const headingOf = (s: (typeof doc.sections)[number]) =>
  "heading" in s ? (s.heading ?? "") : "";
const headings = doc.sections.map(headingOf).join(" | ");

describe("RPT17 evidence-only export parity", () => {
  it("renders as a structured document, not the flat fallback", () => {
    expect(doc.sections.length).toBeGreaterThan(5);
    expect(headings).not.toBe("Summary");
  });

  it("carries every overview section the on-screen report shows", () => {
    for (const heading of [
      "Region / Governorate",
      "Response Quality",
      "Evidence Documents",
      "Summary Status Breakdown",
      "Documents by Type",
      "Themes Across Documents",
      "Evidence Document Register",
    ]) {
      expect(headings).toContain(heading);
    }
  });

  it("carries each document's themes, statements, risks and limitations", () => {
    for (const suffix of [
      "Key Findings",
      "Themes",
      "Supporting Statements",
      "Risks / Concerns",
      "Document Limitations",
    ]) {
      expect(headings).toContain(suffix);
    }
  });

  it("keeps the map's figures as text, since a PDF has no map", () => {
    const geo = doc.sections.find((s) => headingOf(s) === "Region / Governorate");
    expect(JSON.stringify(geo)).toContain("Mapped coverage");
    expect(JSON.stringify(geo)).toContain("Northern Borders");
  });

  it("counts themes across documents, not per document", () => {
    const themes = doc.sections.find((s) => headingOf(s) === "Themes Across Documents");
    // "Water availability" is raised by both documents.
    expect(JSON.stringify(themes)).toContain("Water availability");
  });

  it("carries no scoring anywhere — this report is documents-only", () => {
    const blob = JSON.stringify(doc).toLowerCase();
    for (const banned of ["severityscore", "priorityscore", "toppriorities", "villageneedsindex"]) {
      expect(blob).not.toContain(banned);
    }
  });

  it("survives both exporters", async () => {
    const pdf = renderReportPdf(doc);
    expect(pdf.subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(pdf.length).toBeGreaterThan(1000);

    const xlsx = await renderReportExcel(doc);
    // XLSX is a zip archive.
    expect(xlsx.subarray(0, 2).toString("hex")).toBe("504b");
    expect(xlsx.length).toBeGreaterThan(1000);
  });
});
