import { describe, expect, it } from "vitest";
import { buildReportDoc } from "./report-doc";
import { renderReportExcel } from "./excel-builder";
import { renderReportPdf } from "./pdf-builder";

/**
 * The eight sections the Combined (RPT16) and Evidence (RPT15) reports are
 * required to carry. Four of them — Geography, Evidence, the combined AI
 * narrative and Recommendations — used to be dropped silently: the content was
 * stored but `buildReportDoc` never read those keys, so exported PDFs and
 * spreadsheets simply omitted them.
 */
const RPT16_CONTENT: Record<string, unknown> = {
  header: {
    studyName: "Al Safa Needs Assessment",
    entityName: "Al Noor Community Development Association",
    methodologyVersion: "v1.0",
    cycleNumber: 2,
    dateTime: "2026-07-31T10:00:00.000Z",
  },
  geography: { region: "North Governorate", governorate: "Al Safa" },
  responseQuality: {
    submittedResponses: 260,
    validResponses: 248,
    confidence: "HIGH",
    dontKnowRate: "1.8%",
  },
  severity: {
    label: "High Need",
    overallVillageNeedsIndex: 71.4,
    domains: [
      {
        name: "Water & Sanitation",
        domainCode: "water",
        severityScore: 82.5,
        performanceScore: 76.3,
        weight: 0.35,
        kpiCount: 4,
        confidence: "HIGH",
        confidencePct: 95,
        isCriticalDomain: true,
      },
    ],
  },
  priority: { villagePriorityScore: 68.2, priorityStatus: "HIGH" },
  topPriorities: [
    { rank: 1, needStatement: "Water distribution continuity", score: 86.4, domain: "Water & Sanitation" },
  ],
  evidenceSection: {
    totalDocuments: 1,
    documents: [
      {
        title: "Water Service Field Record",
        documentType: "FIELD_REPORT",
        sourceReferenceId: "AN-CD-WS-2026-047",
        collectedDate: "2026-07-28",
        summaryStatus: "OFFICER_CONFIRMED",
        aiSummary: {
          summary: "The field note states recurring interruptions to the piped supply.",
          keyFindings: [{ finding: "Borehole yield declined during the dry season." }],
        },
      },
    ],
  },
  combinedSummarySection: {
    executiveSummary: "Quantitative scoring and field evidence both point to water continuity.",
    scoreBasedFindings: {
      overallSeverityScore: 71.4,
      priorityScore: 68.2,
      priorityStatus: "HIGH",
      topDomainsOrKpis: [{ name: "Water & Sanitation", score: 82.5 }],
      confidenceDataQualityNote: "248 of 260 responses valid.",
    },
    documentBasedEvidence: [
      {
        documentTitle: "Water Service Field Record",
        sourceReferenceId: "AN-CD-WS-2026-047",
        linkedNeedOrDomain: "Water & Sanitation",
        keyEvidenceFinding: "Participants reported interruptions lasting several days.",
      },
    ],
    domainKpiResults: [
      {
        domainName: "Water & Sanitation",
        severity: 82.5,
        performance: 76.3,
        weight: 0.35,
        confidence: "HIGH",
      },
    ],
  },
  recommendations: [
    "Restore piped supply continuity in the Al Safa district.",
    "Schedule a follow-up qualitative assessment next cycle.",
  ],
};

const AUDIT = [
  { label: "Generated By", value: "Field Officer" },
  { label: "Confirmed By", value: "Research Officer" },
  { label: "Reviewed By", value: "Approver" },
];

describe("RPT16 / RPT15 report document", () => {
  const doc = buildReportDoc("Combined Report", RPT16_CONTENT, AUDIT);
  const headings = doc.sections.map((s) => ("heading" in s ? s.heading : "columns"));
  const allHeadings = doc.sections
    .flatMap((s) => (s.kind === "columns" ? s.children : [s]))
    .map((s) => ("heading" in s ? s.heading : ""));

  it("renders as a structured report rather than a generic flatten", () => {
    // The generic branch emits a single "Summary" keyvalue block; the structured
    // branch is what carries the required sections.
    expect(headings).not.toEqual(["Summary"]);
    expect(doc.headerBand.length).toBeGreaterThan(0);
  });

  it("includes the structured Region / Governorate section", () => {
    expect(allHeadings).toContain("Region / Governorate");
    const geo = doc.sections.find((s) => "heading" in s && s.heading === "Region / Governorate");
    expect(JSON.stringify(geo)).toContain("Al Safa");
  });

  it("includes the evidence document register and per-document AI summary", () => {
    expect(allHeadings).toContain("Evidence Documents");
    expect(allHeadings).toContain("Evidence Document Register");
    expect(allHeadings.some((h) => h.startsWith("Evidence Summary —"))).toBe(true);
    expect(JSON.stringify(doc)).toContain("Borehole yield declined");
  });

  it("includes the combined AI narrative, split into score and evidence halves", () => {
    expect(allHeadings).toContain("Combined Executive Summary");
    expect(allHeadings).toContain("Score-Based Findings");
    expect(allHeadings).toContain("Document-Based Evidence");
    expect(allHeadings).toContain("Domain / KPI Results");
  });

  it("includes top-level recommendations", () => {
    const recs = doc.sections.find((s) => "heading" in s && s.heading === "Recommendations");
    expect(recs).toBeTruthy();
    expect(JSON.stringify(recs)).toContain("Restore piped supply continuity");
  });

  it("carries the audit trail", () => {
    expect(doc.audit.map((a) => a.label)).toEqual([
      "Generated By",
      "Confirmed By",
      "Reviewed By",
    ]);
  });

  it("survives both exporters with the new sections present", async () => {
    const pdf = renderReportPdf(doc);
    expect(pdf.subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(pdf.length).toBeGreaterThan(1000);

    const xlsx = await renderReportExcel(doc);
    // XLSX is a zip archive.
    expect(xlsx.subarray(0, 2).toString("hex")).toBe("504b");
    expect(xlsx.length).toBeGreaterThan(1000);
  });

  // A study with no scoring yet must still produce an evidence report, with the
  // quantitative sections reported as unavailable rather than invented.
  it("still builds when the quantitative half is unavailable", () => {
    const evidenceOnly = {
      ...RPT16_CONTENT,
      severity: { note: "Data not available for this study." },
      priority: { note: "Data not available for this study." },
      responseQuality: { note: "Data not available for this study." },
      topPriorities: [],
      combinedSummarySection: null,
    };
    const built = buildReportDoc("Evidence Report", evidenceOnly, AUDIT);
    const builtHeadings = built.sections
      .flatMap((s) => (s.kind === "columns" ? s.children : [s]))
      .map((s) => ("heading" in s ? s.heading : ""));
    expect(builtHeadings).toContain("Evidence Documents");
    expect(builtHeadings).toContain("Region / Governorate");
    expect(JSON.stringify(built)).not.toContain("78.4");
  });
});
