import { renderReportExcel } from "./excel-builder";
import { renderReportPdf } from "./pdf-builder";
import { buildReportDoc } from "./report-doc";
import type { ReportTypeCode } from "./reports.types";
import type { SupportedLocale } from "../translation/translation.types";
import { localizeDataValues, NO_ALIASES, type MasterDataAliases } from "./i18n/master-data-names";
import { sweepRemainingEnglish, type SweepStats } from "./i18n/sweep-english";
import type { Translator } from "./i18n/translate-content";

// Real generators (see reports.service.ts#generateContent + generators/):
//   RPT01 Individual Survey · RPT02 Collective · RPT03/RPT09 Top-Priority ·
//   RPT04 Sector · RPT06 Region · RPT10 Data-Quality · RPT12 Sharing Status ·
//   RPT13 Executive · RPT14 Village · RPT15 Survey & Dashboard Report ·
//   RPT16 Combined Evidence & Score · RPT17 Evidence Document-Based
// Everything else is still placeholder.
export type PlaceholderReportType = Exclude<
  ReportTypeCode,
  | "RPT01" | "RPT02" | "RPT03" | "RPT04" | "RPT06" | "RPT09" | "RPT10"
  | "RPT12" | "RPT13" | "RPT14" | "RPT15" | "RPT16" | "RPT17"
>;
export const PLACEHOLDER_REPORT_TYPES: PlaceholderReportType[] = [
  "RPT05", "RPT07", "RPT08", "RPT11",
];

/** Narrows a ReportTypeCode to the still-placeholder set — lets the caller tell
 *  "no generator yet, by design" apart from "generator route is missing". */
export function isPlaceholderReportType(code: ReportTypeCode): code is PlaceholderReportType {
  return (PLACEHOLDER_REPORT_TYPES as ReportTypeCode[]).includes(code);
}

// Audit/metadata header (RIO-NFR-008) — every field renders conditionally
// since reviewedBy/reviewedAt are null on any report not yet reviewed, and
// studyTitle is null for org-wide/non-study-scoped report types (see
// REPORT_TYPE_META.requiresStudyId).
export interface ExportAuditMeta {
  generatedAt: string;
  status: string;
  studyTitle: string | null;
  generatedByName: string | null;
  officerConfirmedByName: string | null;
  officerConfirmedAt: string | null;
  reviewedByName: string | null;
  // Reviewer's role name (e.g. "Reviewer/Approver" vs "Center Supervisor") —
  // shown in the audit trail for clarity on who approved, in what capacity.
  reviewedByRole: string | null;
  reviewedAt: string | null;
  archivedAt: string | null;
  // RIO-RPT-001 acceptance criterion 5: the methodology/data version the report
  // was generated against is stamped alongside the timestamp and the generating
  // user. Without it a figure cannot be reconciled after the fact — a reader
  // has no way to know which version of the scoring rules produced it, so a
  // later methodology change makes every archived report unverifiable.
  //
  // Resolved from the report content's own header (the version the generator
  // actually used), never from the study's current version, which may have
  // moved on since. Null only when the content carries no header at all.
  methodologyVersion: string | null;
}

// Compact, human-readable stamp (e.g. "22 Jul 2026, 10:30") instead of raw ISO.
function fmtStamp(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
}

function auditMetaLines(meta: ExportAuditMeta): Array<{ field: string; value: string }> {
  const rows: Array<{ field: string; value: string }> = [
    { field: "Generated At", value: fmtStamp(meta.generatedAt) },
    { field: "Status", value: meta.status },
  ];
  if (meta.studyTitle) rows.push({ field: "Study", value: meta.studyTitle });
  if (meta.generatedByName) rows.push({ field: "Generated By", value: meta.generatedByName });
  // Sits immediately after "Generated By" so the three AC-5 facts — when, who,
  // against which methodology — read as one provenance line.
  if (meta.methodologyVersion) rows.push({ field: "Methodology Version", value: meta.methodologyVersion });
  // Two-actor approval trail (Officer confirms → Reviewer approves).
  if (meta.officerConfirmedByName) rows.push({ field: "Officer Confirmed By", value: meta.officerConfirmedByName });
  if (meta.officerConfirmedAt) rows.push({ field: "Officer Confirmed At", value: fmtStamp(meta.officerConfirmedAt) });
  if (meta.reviewedByName) rows.push({ field: "Reviewed By", value: meta.reviewedByName });
  if (meta.reviewedByRole) rows.push({ field: "Reviewer Role", value: meta.reviewedByRole });
  if (meta.reviewedAt) rows.push({ field: "Reviewed At", value: fmtStamp(meta.reviewedAt) });
  if (meta.archivedAt) rows.push({ field: "Archived At", value: fmtStamp(meta.archivedAt) });
  return rows;
}

// Real, openable, properly formatted PDF/Excel files generated from the
// report's own `content` (see reports.service.ts#generateContent) —
// RIO-NFR-007 (Arabic RTL) and the final bespoke per-report-type visual
// design are still a documented follow-up (the latter pending Karthika's
// Village Assessment Report viewer); this covers real pagination, section
// headings, and bordered tables generically today (RIO-NFR-008).
export async function buildExportStub(
  format: "pdf" | "excel",
  report: { id: string; title: string; reportType: string; content: Record<string, unknown> },
  meta: ExportAuditMeta,
  locale: SupportedLocale = "en",
  /** Master-data names in the caller's locale. Empty for English, and empty is
   *  a no-op, so the English path is unchanged. See i18n/master-data-names.ts
   *  for why this arrives here rather than being read by the provider. */
  aliases: MasterDataAliases = NO_ALIASES,
  /** When supplied, a final pass translates anything still English in the
   *  finished document — including strings the renderers compose themselves,
   *  which no content-level pass can reach. Omitted, the export behaves exactly
   *  as before. */
  translator?: Translator,
): Promise<{ filename: string; contentType: string; body: Buffer; sweep?: SweepStats }> {
  const auditRows = auditMetaLines(meta).map((r) => ({ label: r.field, value: r.value }));
  // The audit labels above are still composed in English here and translated
  // inside buildReportDoc by the same catalogue lookup as every other label —
  // so this function has one notion of "a label", not two.
  // Two passes, in this order and deliberately separate: the catalogue
  // translates LABEL positions, the alias map translates VALUE positions. A
  // single pass cannot do both — the catalogue's English keys collide with real
  // data (the severity band "CRITICAL" against the "Critical" column heading),
  // so the two must not see each other's territory.
  let doc = localizeDataValues(
    buildReportDoc(report.title, report.content, auditRows, locale),
    aliases,
  );

  // Last layer before rendering. The three passes above are precise and only
  // cover what was declared; this catches the rest, cheapest source first, so
  // the AI only sees genuinely novel prose.
  let sweep: SweepStats | undefined;
  if (translator) {
    const swept = await sweepRemainingEnglish(doc, locale, { aliases, translator });
    doc = swept.doc;
    sweep = swept.stats;
  }
  const ext = format === "pdf" ? "pdf" : "xlsx";
  const filename = `${report.reportType}-${report.id}.${ext}`;

  if (format === "pdf") {
    return { filename, contentType: "application/pdf", body: renderReportPdf(doc, "pages", locale), sweep };
  }
  return {
    filename,
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    body: await renderReportExcel(doc, locale),
    sweep,
  };
}

// RPT13's narrative is NOT composed here. It comes from
// ReportSummaryDataProvider.getExecutiveReport() — the real AI narrative,
// with providers/compose-executive-summary.ts's deterministic, figure-derived
// summary as the fallback when the AI is unavailable. A canned
// buildExecutiveSummaryNarrative() used to live at this spot and emitted
// "Executive summary (placeholder) for ..."; it had no callers by the time
// the real generator landed and has been deleted rather than left where a
// future edit could wire it back in.

// RPT-02..13 content contract: a fixed shape (summary / sections / metrics)
// that today holds canned placeholder copy and later swaps to real LLM
// output with no schema or consumer change — same "body changes, contract
// doesn't" pattern as getSurveyDefinition. RPT-01 is out of scope (kept on
// its real-data path in reports.service.ts) until it gets its own table.
const PLACEHOLDER_REPORT_META: Record<
  PlaceholderReportType,
  {
    title: string;
    summary: string;
    findings: string[];
    recommendations: string[];
  }
> = {

  RPT05: {
    title: "Governorate-wise Needs Report",
    summary:
      "Distribution of identified needs across surveyed governorates.",
    findings: [
      "Governorate A recorded the highest concentration of critical needs.",
      "Governorate C demonstrated improved service availability.",
      "Governorate D reported recurring sanitation concerns.",
    ],
    recommendations: [
      "Prioritize interventions for Governorate A.",
      "Monitor sanitation improvements in Governorate D.",
    ],
  },

  RPT07: {
    title: "Gender-based Needs Analysis",
    summary:
      "Comparison of identified needs across available gender-specific responses.",
    findings: [
      "Healthcare-related concerns were more frequently reported by women.",
      "Employment support appeared consistently across both groups.",
      "Education priorities remained similar across respondents.",
    ],
    recommendations: [
      "Consider gender-specific intervention planning.",
      "Review demographic coverage in future surveys.",
    ],
  },

  RPT08: {
    title: "KPI Results Report",
    summary:
      "Summary of current KPI measurements for the selected reporting scope.",
    findings: [
      "68% of monitored indicators met the expected threshold.",
      "Access to basic services showed gradual improvement.",
      "Three indicators remain below the target level.",
    ],
    recommendations: [
      "Review underperforming indicators.",
      "Track KPI trends across future assessment cycles.",
    ],
  },



  RPT11: {
    title: "Previous Studies Summary",
    summary:
      "Overview of completed studies available for historical comparison.",
    findings: [
      "Five previous studies matched the selected criteria.",
      "Recurring needs were observed across multiple assessment cycles.",
      "Infrastructure concerns remained consistent over time.",
    ],
    recommendations: [
      "Compare historical trends before planning interventions.",
      "Review changes between assessment cycles.",
    ],
  },

};

export function buildPlaceholderReport(reportType: PlaceholderReportType): { title: string; content: Record<string, unknown> } {
  const meta = PLACEHOLDER_REPORT_META[reportType];
  return {
    title: meta.title,
    content: {
      summary: meta.summary,
      sections: [
        { title: "Overview", content: meta.summary },
        { title: "Key Findings", content: meta.findings },
        { title: "Recommendations", content: meta.recommendations },
      ],
      metrics: [
        { label: "Needs Identified", value: 24 },
        { label: "Priority Level", value: "High" },
        { label: "Data Confidence", value: "92%" },
        { label: "Assessment Coverage", value: "8 Governorates" },
      ],
      generatedBy: "RIO AI",
      generatedAt: new Date().toISOString(),
      isPlaceholder: true,
    },
  };
}
