import { describe, expect, it } from "vitest";
import { buildReportDoc, type DocSection, type ReportDoc } from "./report-doc";
import { keyForEnglish, label } from "./i18n/report-labels";
import { StubReportDataProvider } from "./providers/__fixtures__/report-content.fixtures";
import type { GeneratorCtx } from "./generators";
import { individualSurveyGenerator } from "./generators/individual-survey.generator";
import { villageGenerator } from "./generators/village.generator";
import { dataQualityGenerator } from "./generators/data-quality.generator";
import { topPriorityGenerator } from "./generators/top-priority.generator";
import { executiveGenerator } from "./generators/executive.generator";
import { sectorGenerator } from "./generators/sector.generator";
import { regionGenerator } from "./generators/region.generator";

// End-to-end check of the label half of RIO-NFR-007, asserted on the built
// ReportDoc: the renderers are locale-agnostic by design (a document reaches
// them already translated), so this is the last point where the two languages
// are comparable without parsing PDF bytes.
//
// Coverage is asserted as "nothing left", not as a threshold. It began at 53 of
// 96 rendered headings: the rest were either static strings with no catalogue
// key, or headings report-doc.ts composes at runtime from data
// ("Health — Domain Detail") which no text match can reach. Both are now
// closed, so a new untranslated heading or column fails the build rather than
// shipping English inside an Arabic report.

const AUDIT = [
  { label: "Generated At", value: "08 Sep 2026, 10:30" },
  { label: "Status", value: "released" },
  { label: "Generated By", value: "A. Officer" },
  { label: "Reviewed By", value: "R. Reviewer" },
];

const ARABIC = /[؀-ۿ]/;

const ctx = (over: Partial<GeneratorCtx> = {}): GeneratorCtx => ({
  provider: new StubReportDataProvider(),
  orgId: "org-1",
  studyId: "study-1",
  studyTitle: "Ad-Dilam Baseline",
  filters: {},
  ...over,
});

const REPORTS = [
  ["RPT01", () => individualSurveyGenerator(ctx({ surveyId: "survey-1" }))],
  ["RPT14", () => villageGenerator(ctx({ filters: { villageId: "village-1" } }))],
  ["RPT10", () => dataQualityGenerator(ctx())],
  ["RPT03/09", () => topPriorityGenerator(ctx())],
  ["RPT13", () => executiveGenerator(ctx())],
  ["RPT04", () => sectorGenerator(ctx())],
  ["RPT06", () => regionGenerator(ctx())],
] as const;

// Headings composed at runtime from a DATA value plus a fixed suffix —
// "Health — Domain Detail". These cannot be reached by a text match (the text
// differs per domain), so localizeKnownLabel peels the name off and translates
// only the fixed half through a parameterised catalogue key. The NAME itself
// stays as the generator produced it: localising master data is the provider's
// job via Domain.nameAr, not the label layer's.
const COMPOSED_WITH_DATA = /— (Domain|Indicator) Detail$/;

// Labels whose correct Arabic IS the English string. "#" is the rank column in
// both languages, so "did it change?" is the wrong question for them and a
// script test would report a correct translation as a failure.
const SAME_IN_BOTH = new Set(['#']);

function headings(sections: readonly DocSection[]): string[] {
  return sections.flatMap((s): string[] => {
    if (s.kind === "columns") return headings(s.children);
    // anchor and breadcrumb carry no heading of their own.
    if (!("heading" in s) || !s.heading) return [];
    return [s.heading];
  });
}

async function docs(run: () => Promise<{ title: string; content: Record<string, unknown> }>) {
  const { title, content } = await run();
  return {
    en: buildReportDoc(title, content, AUDIT),
    ar: buildReportDoc(title, content, AUDIT, "ar"),
  };
}

describe("Arabic export labels", () => {
  for (const [code, run] of REPORTS) {
    it(`${code} translates every heading the catalogue knows`, async () => {
      const { en, ar } = await docs(run);
      const arHeadings = headings(ar.sections);

      // Pair each English heading with its Arabic counterpart positionally, so
      // a heading that HAS a key but was skipped by the walker is caught.
      // Asserting only "is it Arabic" would let an unkeyed heading mask that.
      const missed = headings(en.sections)
        .map((h, i) => ({ h, out: arHeadings[i]! }))
        .filter(({ h, out }) => keyForEnglish(h) !== null && !ARABIC.test(out))
        .map(({ h }) => h);

      expect(missed, `${code}: keyed headings left in English`).toEqual([]);
    });

    it(`${code} translates its audit trail`, async () => {
      const { ar } = await docs(run);
      // RIO-NFR-008's provenance block is what a reader checks to trust the
      // document, so it is exactly the part that must not be half-English.
      for (const row of ar.audit) expect(ARABIC.test(row.label), row.label).toBe(true);
    });

    it(`${code} leaves the English build unchanged`, async () => {
      const { en } = await docs(run);
      expect(headings(en.sections).some((h) => ARABIC.test(h))).toBe(false);
      expect(en.audit.map((r) => r.label)).toEqual(AUDIT.map((r) => r.label));
    });
  }

  it("translates labels but never the data beside them", async () => {
    const { en, ar } = await docs(REPORTS[0][1]);

    const cells = (d: ReportDoc) =>
      d.sections.flatMap((s) => (s.kind === "table" ? s.rows.flat() : []));
    const values = (d: ReportDoc) =>
      d.sections.flatMap((s) => (s.kind === "keyvalue" ? s.rows.map((r) => r.value) : []));

    // Severity bands, domain names, scores and dates are data — and some of
    // them collide by text with real labels ("CRITICAL" against the "Critical"
    // column heading), so a careless localizer would rewrite them invisibly.
    expect(cells(ar)).toEqual(cells(en));
    expect(values(ar)).toEqual(values(en));

    // ...while the column names beside those untouched cells did move. Checked
    // positionally against the English build for the same reason as headings:
    // a column that HAS a key but was skipped must not hide behind one that has
    // none. The two that have no key are named, not waved past.
    const cols = (d: ReportDoc) => d.sections.flatMap((s) => (s.kind === "table" ? s.columns : []));
    const enCols = cols(en);
    const arCols = cols(ar);
    expect(enCols.length).toBeGreaterThan(0);

    // Compared against the catalogue's own Arabic value rather than "does it
    // contain Arabic script": some labels are legitimately identical in both
    // languages. col.rank is "#" in English and "#" in Arabic, and a
    // script test would report that correct translation as a failure.
    const skipped = enCols.filter((c, i) => {
      const key = keyForEnglish(c);
      return key !== null && arCols[i] !== label(key, "ar");
    });
    expect(skipped, "keyed column names left in English").toEqual([]);

    // Every column the nine reports print now has a key. Asserted as an empty
    // list rather than deleted, so a newly-added column with no catalogue entry
    // fails here instead of quietly shipping English into an Arabic export.
    const unkeyed = [...new Set(enCols.filter((c) => keyForEnglish(c) === null))].sort();
    expect(unkeyed, "column names still needing a catalogue key").toEqual([]);
  });

  it("leaves no untranslated heading or column in any of the nine reports", async () => {
    // The headline claim of the label half of RIO-NFR-007, asserted rather
    // than asserted-about. This started at 53 of 96 headings; the gap was
    // closed by adding catalogue keys and by teaching localizeKnownLabel the
    // two composed-heading shapes.
    const headingsLeft = new Set<string>();
    const columnsLeft = new Set<string>();

    for (const [, run] of REPORTS) {
      const { en, ar } = await docs(run);

      headings(en.sections).forEach((h, i) => {
        const out = headings(ar.sections)[i]!;
        if (out === h && !SAME_IN_BOTH.has(h)) headingsLeft.add(h);
      });

      const cols = (d: ReportDoc) =>
        d.sections.flatMap((s) => (s.kind === "table" ? s.columns : []));
      const enCols = cols(en);
      const arCols = cols(ar);
      enCols.forEach((c, i) => {
        if (arCols[i] === c && !SAME_IN_BOTH.has(c)) columnsLeft.add(c);
      });
    }

    expect([...headingsLeft].sort(), "headings still rendering in English").toEqual([]);
    expect([...columnsLeft].sort(), "column names still rendering in English").toEqual([]);
  });

  it("translates a composed drill-down heading without touching its data", async () => {
    const { en, ar } = await docs(REPORTS[0][1]);

    const composed = headings(en.sections).filter((h) => COMPOSED_WITH_DATA.test(h));
    expect(composed.length, "fixture should produce drill-down pages").toBeGreaterThan(0);

    for (const h of composed) {
      const out = headings(ar.sections)[headings(en.sections).indexOf(h)]!;
      const name = h.replace(COMPOSED_WITH_DATA, "").trim();
      // The fixed half moved to Arabic...
      expect(ARABIC.test(out), `${h} -> ${out}`).toBe(true);
      // ...and the domain/indicator name came through untouched.
      expect(out.startsWith(name), `${out} should still start with "${name}"`).toBe(true);
    }
  });
});

describe("contents page and chapter furniture", () => {
  // Found by looking at a rendered Arabic PDF, not by the ReportDoc audit:
  // pdf-builder.ts composes some of its own text AFTER the document has been
  // localised, so those strings never reached the label pass at all.
  it("translates every chapter name and its count summary", async () => {
    const { title, content } = await REPORTS[0][1]();
    const ar = buildReportDoc(title, content, AUDIT, "ar");

    expect(ar.chapters?.length, "fixture should produce a chaptered report").toBeGreaterThan(1);
    for (const c of ar.chapters ?? []) {
      expect(ARABIC.test(c.name), `chapter name "${c.name}"`).toBe(true);
      // "3 rows · 1 chart" — a Latin figure in front of a translated unit.
      expect(ARABIC.test(c.summary), `chapter summary "${c.summary}"`).toBe(true);
    }
  });

  it("keeps the figures in the chapter counts as Latin digits", async () => {
    const { title, content } = await REPORTS[0][1]();
    const en = buildReportDoc(title, content, AUDIT);
    const ar = buildReportDoc(title, content, AUDIT, "ar");

    const digits = (s: string) => (s.match(/\d+/g) ?? []).join(",");
    (en.chapters ?? []).forEach((c, i) => {
      expect(digits(ar.chapters![i]!.summary)).toBe(digits(c.summary));
    });
  });
});
