import type { AppLocale } from './locale';

/**
 * Server-side message catalogue for exported reports.
 *
 * Separate from the frontend's `messages/*.json` on purpose (RIO-RPT-001
 * layer 2, option A). The report vocabulary is largely disjoint from the UI
 * vocabulary, and sharing one catalogue across the two would couple their
 * deploy cycles for the sake of a handful of overlapping words.
 *
 * Rules for anything added here:
 *
 *  1. Keys are dotted and grouped by area — `audit.*`, `band.*`, `report.*`.
 *  2. Parameters are `{named}`, never positional, so a translator can reorder
 *     them. Arabic routinely needs a different clause order than English; a
 *     positional placeholder would make that impossible to express.
 *  3. Every key present in `en` must be present in `ar`. The type below
 *     enforces it at compile time — a missing Arabic string is a build error,
 *     not a silent English word inside an Arabic report, which is exactly the
 *     failure this whole effort exists to remove.
 *
 * TRANSLATION STATUS: the Arabic below covers report chrome — labels, headings,
 * bands, provenance. It is deliberately NOT the methodology vocabulary (domain,
 * sub-domain, indicator, KPI, governorate and centre names). Those are the
 * client's to supply and must not be invented here; they live in `nameAr`
 * columns on their own reference tables. See RIO-I18N-003 §6.
 */

const en = {
  // ── Provenance / audit header (RIO-NFR-008, RIO-RPT-001 AC 5) ──
  'audit.generatedAt': 'Generated At',
  'audit.status': 'Status',
  'audit.study': 'Study',
  'audit.generatedBy': 'Generated By',
  'audit.methodologyVersion': 'Methodology Version',
  'audit.officerConfirmedBy': 'Officer Confirmed By',
  'audit.officerConfirmedAt': 'Officer Confirmed At',
  'audit.reviewedBy': 'Reviewed By',
  'audit.reviewerRole': 'Reviewer Role',
  'audit.reviewedAt': 'Reviewed At',
  'audit.archivedAt': 'Archived At',
  // Which language edition of an approved report this file is. Stamped next to
  // the methodology version so a shared file states what it is — two files from
  // one approval must be distinguishable without opening both.
  'audit.exportLanguage': 'Language Edition',
  'audit.language.en': 'English',
  'audit.language.ar': 'Arabic',

  // ── Severity bands (providers/severity-bands.ts#severityBandOf) ──
  'band.severity.CRITICAL': 'Critical',
  'band.severity.HIGH': 'High',
  'band.severity.MEDIUM': 'Medium',
  'band.severity.LOW': 'Low',

  // ── Priority status (severityBandOf's inverted twin) ──
  'band.priority.HIGH': 'High',
  'band.priority.MEDIUM': 'Medium',
  'band.priority.LOW': 'Low',

  // ── Don't-know rate bands (dontKnowBandOf) ──
  'band.dontKnow.negligible': 'negligible',
  'band.dontKnow.moderate': 'moderate',
  'band.dontKnow.elevated': 'elevated',
  'band.dontKnow.high': 'high',

  // ── Confidence flag (confidenceFlagOf) ──
  'band.confidence.LOW': 'Low',
  'band.confidence.STANDARD': 'Standard',

  // ── Confidence reasons (composeConfidenceReason) ──
  // Five sentence forms, one per condition that can fire. These were English
  // string literals built in code; they are quoted VERBATIM by the report
  // prompts, so they must arrive already in the report's language — the model
  // must never be the thing that translates them.
  'confidence.smallSample':
    'Small sample: {n} valid response(s), below the {required} required for STANDARD confidence.',
  'confidence.belowCoverageTarget':
    "Below coverage target: {n} valid response(s), below the {required} required for this study's population at the configured confidence level and margin of error.",
  'confidence.elevatedDontKnow':
    "Elevated don't-know rate: {rate}% exceeds the {threshold}% threshold.",
  'confidence.highCompleteness': 'High response completeness.',
  'confidence.dontKnowDidNotContribute':
    "The don't-know rate of {rate}% is {band} and did not contribute to this rating.",

  // ── Scale direction note (PRIORITY_DIRECTION_NOTE) ──
  'note.priorityDirection':
    'The Village Priority Score is performance-based: LOWER means more urgent. It runs opposite to both the Severity scores and the per-need Priority Score column on this page, where HIGHER means more urgent.',

  // ── Strings the report prompts instruct the model to emit verbatim ──
  // Supplied to the model per-locale in the user turn rather than hardcoded in
  // the system prompt, so the system prompt stays static and its hash stable
  // (RIO-I18N-003 §3.3, §6.2).
  'narrative.cycle1TrendPending': 'Cycle 1 assessment — Trend Pending.',
  'narrative.dataNotAvailable': 'Data not available in this assessment.',
  'narrative.dataNotAvailableInDocument': 'Data not available in this document.',
  'narrative.trendPendingFirstCycle': 'Trend pending — first assessment cycle.',
  // The deterministic fallback narrative must say what it is. A reader who
  // assumes a generated paragraph came from the model is being misled about how
  // much analysis stands behind it.
  'narrative.generatedNotAi':
    'This summary was composed automatically from the report figures. It is not AI-generated analysis.',

  // ── Deterministic fallback narrative (providers/build-unified-rpt01.ts) ──
  // Composed in code from the report's own figures whenever no AI narrative
  // exists. It is prose, so it cannot be substituted at export time like a
  // label — it has to be composed in the right language from the start.
  'narrative.det.scored':
    "This survey-only assessment scored {measured} of {total} indicator(s) across {domains} of the methodology's {allDomains} domains.",
  'narrative.det.assessedDomains': 'Assessed domains: {list}.',
  'narrative.det.noMeasurableSeverity': 'No domain returned a measurable severity.',
  'narrative.det.priorityNotCalculable': 'Village Priority Score is not calculable. {reason}',
  'narrative.det.priorityScore': 'Village Priority Score is {score} ({status}). {note}',
  'narrative.det.confidence': 'Confidence is {flag}. {reason}',
  'narrative.det.unassessedNote':
    'Domains that were not assessed carry no score; their absence is not a finding of low need.',
  'narrative.det.finding':
    '{rank}. {indicator} ({domain} → {subDomain}) — severity {score} {band}, confidence {confidence}, gap type {gapType}.',
  'narrative.det.noFindings':
    'No indicator returned a measurable severity, so no findings can be ranked.',
  'narrative.det.notClassified': 'not classified',

  // ── Collective dashboard narrative (RPT02, providers/report-summary-data) ──
  'narrative.coll.noNeeds': 'No needs have been recorded for this organisation yet.',
  'narrative.coll.noScoredData': 'There is no scored data to summarise.',
  'narrative.coll.noResponsesAssessed': 'No responses have been assessed.',
  'narrative.coll.trendNoCycle': 'Trend pending — no assessment cycle has completed.',
  'narrative.coll.recorded': '{needs} need(s) recorded, of which {scored} are scored.',
  'narrative.coll.highPriority': '{high} are High priority',
  'narrative.coll.leadingDomains': '; the highest-severity needs fall under {domains}.',
  'narrative.coll.finding': '{rank}. {label} ({domain}, severity {score})',
  'narrative.coll.noRanking':
    'No needs have been scored yet, so no priority ranking is available.',
  'narrative.coll.noAnomalies': 'No response-quality anomalies were flagged.',
  'narrative.coll.recPrioritise': 'Prioritise interventions in {domain}.',
  'narrative.coll.recFieldValidate': 'Field-validate the findings flagged as low confidence.',
  'narrative.coll.recClearQueue':
    'Clear the overdue reviewer queue — SLA compliance is {pct}%.',

  // ── Masking alerts (report-doc.ts) ──
  // Composed in code at export time from the report's own figures, so they are
  // prose that no lookup table can substitute after the fact — they have to be
  // built in the right language.
  'note.domainMasking':
    '{count} domain(s) average a milder band than their worst KPI: {domains}. Per the methodology, a critical need surfaces regardless of its domain average — read the Max KPI Severity column, not the average, for these domains.',
  'note.domainMaskingWorst': '{domain} (worst: {kpi} at {severity})',
  'note.geographicMasking':
    '{count} governorate(s) average a milder band than their worst village: {governorates}. Read the Worst Village column, not the average, for these rows.',

  // ── Contents-page chapter summaries (report-doc.ts#chapterSummary) ──
  // Arabic marks singular/dual/plural differently from English's "1 row / 2
  // rows", so these are three keys rather than one with a plural suffix glued
  // on. `count` is still passed to the singular and dual forms so a translator
  // can put the figure back if their wording needs it.
  'chapter.rows.one': '1 row',
  'chapter.rows.two': '2 rows',
  'chapter.rows.many': '{count} rows',
  'chapter.charts.one': '1 chart',
  'chapter.charts.two': '2 charts',
  'chapter.charts.many': '{count} charts',
  'chapter.summary': 'Summary',
  'note.demographicsPending':
    'Not available — demographic (gender / rural) capture is pending. This chart will populate once demographic data is collected.',

  // ── Calculation-basis explanations (providers/build-unified-rpt01.ts) ──
  // The methodology, written out in prose so a reader can check a figure
  // against the rule that produced it. Composed in code from the report's own
  // thresholds, so like the narratives they have to be built in the right
  // language rather than substituted afterwards.
  'calc.coverageBasis':
    'Computed over the {domains} assessed domain(s), whose methodology weights sum to {weight} of 1.00. The weighted mean is renormalised across those domains; unassessed domains contribute nothing and are not treated as scoring well.',
  'calc.coverageBasisUnavailable':
    'Coverage basis unavailable — no domain priority weights are configured for this methodology version, so no weighted score could be produced.',
  'calc.needsIndexFormula':
    'Needs Index = mean of the measured DOMAIN severities. A domain is the mean of its measured sub-domains, a sub-domain the mean of its measured indicators, an indicator the mean of its measured KPIs, a KPI the mean of its scored answers. Unmeasured levels are skipped at every step, never counted as 0.',
  'calc.priorityScoreFormula':
    'Priority Score = Σ((100 − domain severity) × domain weight) renormalised over the assessed domains\' weight sum. Performance-based, so LOWER means more urgent.',
  'calc.priorityNotCalculable':
    'Priority Score: not calculable — no stored village priority assessment.',
  'calc.severityBandingRule':
    'Severity 0–100 (higher = worse): ≥70 CRITICAL, ≥50 HIGH, ≥30 MEDIUM, <30 LOW. A measured 0 is LOW; an unmeasured indicator is null and shown as \'—\'.',
  'calc.confidenceRule':
    'Confidence is LOW when valid responses < {minSample} OR the don\'t-know rate > {dkThreshold}%; otherwise STANDARD. The stated reason names only the condition that actually fired.',
  'calc.equityRule':
    'Equity flag fires when the severity spread (max − min) across a dimension\'s groups ≥ {spread} points AND every compared group has n ≥ {minGroup}. When no dimension clears the group minimum the flag is false and the reason says the sample was too small — it is not a finding of no inequity.',

  // ── Report type names (REPORT_CATALOG) ──
  'report.RPT01': 'Individual Survey Report',
  'report.RPT02': 'Collective Report / Dashboard',
  'report.RPT03': 'Top-Priority Report',
  'report.RPT04': 'Domain-wise Needs',
  'report.RPT05': 'Governorate-wise Needs',
  'report.RPT06': 'Region/Governorate Filtering',
  'report.RPT07': 'Gender-wise Needs',
  'report.RPT08': 'KPI Results',
  'report.RPT09': 'Priority Ranking',
  'report.RPT10': 'Data-Quality Report',
  'report.RPT11': 'Previous Studies View',
  'report.RPT12': 'Report Sharing Status',
  'report.RPT13': 'Executive Summary',
  'report.RPT14': 'Village Report',
  'report.RPT15': 'Survey & Dashboard Report',
  'report.RPT16': 'Combined Evidence & Score Report',
  'report.RPT17': 'Evidence Document-Based Report',

  // ── Report titles that name their subject ──
  'report.title.village': 'Village Report — {village}',
  'report.title.scoped': '{report} — {scope}',

  // ── Common table/section chrome ──
  'label.value': 'Value',
  'label.field': 'Field',
  'label.count': 'Count',
  'label.percentage': 'Percentage',
  'label.severityScore': 'Severity Score',
  'label.priorityScore': 'Priority Score',
  'label.priorityStatus': 'Priority Status',
  'label.confidence': 'Confidence',
  'label.domain': 'Domain',
  'label.subDomain': 'Sub-domain',
  'label.village': 'Village',
  'label.governorate': 'Governorate',
  'label.region': 'Region',
  'label.center': 'Centre',
  'label.need': 'Need',
  'label.responses': 'Responses',
  'label.affectedPopulation': 'Affected Population',
  'label.notAvailable': 'Not available',
  'label.item': 'Item',
  'label.detail': 'Detail',
  'label.summary': 'Summary',
  'label.metric': 'Metric',
  'label.difference': 'Difference',
  'label.viewDetail': 'View detail',
  'sheet.summary': 'Summary',
  'label.backToSummary': 'Back to Summary',
  'label.open': 'Open',
  'label.backToContents': 'Back to Contents',
  'label.contents': 'Contents',
  'label.contentsHint': 'Click a box to open that section. Each section has a link back to this page.',
} as const;

export type MessageKey = keyof typeof en;

/**
 * Arabic report chrome.
 *
 * NOT reviewed by a native speaker or by the client yet — see the translation
 * note in this file's header. Treat every string here as a draft pending the
 * client's authoritative terminology, and do not ship an Arabic export to a
 * client without that review. It is here so the plumbing can be built and
 * tested against real strings rather than placeholders, which is the only way
 * the layout problems (string length, direction, digit shaping) surface early.
 */
const ar: Record<MessageKey, string> = {
  'audit.generatedAt': 'تاريخ الإنشاء',
  'audit.status': 'الحالة',
  'audit.study': 'الدراسة',
  'audit.generatedBy': 'أنشأه',
  'audit.methodologyVersion': 'إصدار المنهجية',
  'audit.officerConfirmedBy': 'اعتمده الموظف',
  'audit.officerConfirmedAt': 'تاريخ اعتماد الموظف',
  'audit.reviewedBy': 'راجعه',
  'audit.reviewerRole': 'دور المراجع',
  'audit.reviewedAt': 'تاريخ المراجعة',
  'audit.archivedAt': 'تاريخ الأرشفة',
  'audit.exportLanguage': 'نسخة اللغة',
  'audit.language.en': 'الإنجليزية',
  'audit.language.ar': 'العربية',

  'band.severity.CRITICAL': 'حرج',
  'band.severity.HIGH': 'مرتفع',
  'band.severity.MEDIUM': 'متوسط',
  'band.severity.LOW': 'منخفض',

  'band.priority.HIGH': 'مرتفعة',
  'band.priority.MEDIUM': 'متوسطة',
  'band.priority.LOW': 'منخفضة',

  'band.dontKnow.negligible': 'ضئيلة',
  'band.dontKnow.moderate': 'متوسطة',
  'band.dontKnow.elevated': 'مرتفعة',
  'band.dontKnow.high': 'عالية',

  'band.confidence.LOW': 'منخفضة',
  'band.confidence.STANDARD': 'قياسية',

  'confidence.smallSample':
    'عينة صغيرة: {n} استجابة صالحة، وهي أقل من {required} المطلوبة لمستوى الثقة القياسي.',
  'confidence.belowCoverageTarget':
    'أقل من هدف التغطية: {n} استجابة صالحة، وهي أقل من {required} المطلوبة لحجم مجتمع هذه الدراسة عند مستوى الثقة وهامش الخطأ المحددين.',
  'confidence.elevatedDontKnow':
    'نسبة مرتفعة من إجابات «لا أعرف»: {rate}% تتجاوز الحد المسموح به وهو {threshold}%.',
  'confidence.highCompleteness': 'اكتمال مرتفع في الاستجابات.',
  'confidence.dontKnowDidNotContribute':
    'نسبة إجابات «لا أعرف» البالغة {rate}% تُعد {band} ولم تؤثر في هذا التقييم.',

  'note.priorityDirection':
    'درجة أولوية القرية مبنية على الأداء: الأقل يعني الأكثر إلحاحًا. وهي تسير في الاتجاه المعاكس لدرجات الشدة ولعمود درجة الأولوية لكل احتياج في هذه الصفحة، حيث يعني الأعلى الأكثر إلحاحًا.',

  'narrative.cycle1TrendPending': 'تقييم الدورة الأولى — الاتجاه قيد الانتظار.',
  'narrative.dataNotAvailable': 'البيانات غير متوفرة في هذا التقييم.',
  'narrative.dataNotAvailableInDocument': 'البيانات غير متوفرة في هذا المستند.',
  'narrative.trendPendingFirstCycle': 'الاتجاه قيد الانتظار — دورة التقييم الأولى.',
  'narrative.generatedNotAi':
    'أُعد هذا الملخص تلقائيًا من أرقام التقرير، وهو ليس تحليلًا مولدًا بالذكاء الاصطناعي.',

  'narrative.det.scored':
    'قيّم هذا التقييم المبني على الاستبيان {measured} من أصل {total} مؤشرًا عبر {domains} من أصل {allDomains} مجالات في المنهجية.',
  'narrative.det.assessedDomains': 'المجالات المُقيّمة: {list}.',
  'narrative.det.noMeasurableSeverity': 'لم يسجل أي مجال درجة شدة قابلة للقياس.',
  'narrative.det.priorityNotCalculable': 'درجة أولوية القرية غير قابلة للاحتساب. {reason}',
  'narrative.det.priorityScore': 'درجة أولوية القرية هي {score} ({status}). {note}',
  'narrative.det.confidence': 'مستوى الثقة {flag}. {reason}',
  'narrative.det.unassessedNote':
    'المجالات التي لم تُقيّم لا تحمل درجة، وغيابها ليس دليلاً على انخفاض الاحتياج.',
  'narrative.det.finding':
    '{rank}. {indicator} ({domain} → {subDomain}) — الشدة {score} {band}، مستوى الثقة {confidence}، نوع الفجوة {gapType}.',
  'narrative.det.noFindings':
    'لم يسجل أي مؤشر درجة شدة قابلة للقياس، لذا لا يمكن ترتيب أي نتائج.',
  'narrative.det.notClassified': 'غير مصنف',

  'narrative.coll.noNeeds': 'لم تُسجل أي احتياجات لهذه المؤسسة بعد.',
  'narrative.coll.noScoredData': 'لا توجد بيانات مُقيّمة لتلخيصها.',
  'narrative.coll.noResponsesAssessed': 'لم يتم تقييم أي استجابات.',
  'narrative.coll.trendNoCycle': 'الاتجاه قيد الانتظار — لم تكتمل أي دورة تقييم.',
  'narrative.coll.recorded': 'تم تسجيل {needs} احتياجًا، منها {scored} مُقيّمة.',
  'narrative.coll.highPriority': '{high} منها ذات أولوية مرتفعة',
  'narrative.coll.leadingDomains': '؛ وتقع الاحتياجات الأشد ضمن {domains}.',
  'narrative.coll.finding': '{rank}. {label} ({domain}، الشدة {score})',
  'narrative.coll.noRanking':
    'لم يتم تقييم أي احتياجات بعد، لذا لا يتوفر ترتيب للأولويات.',
  'narrative.coll.noAnomalies': 'لم تُرصد أي حالات شاذة في جودة الاستجابات.',
  'narrative.coll.recPrioritise': 'إيلاء الأولوية للتدخلات في {domain}.',
  'narrative.coll.recFieldValidate': 'التحقق ميدانيًا من النتائج المُعلمة بثقة منخفضة.',
  'narrative.coll.recClearQueue':
    'تصفية قائمة المراجعة المتأخرة — نسبة الالتزام باتفاقية مستوى الخدمة {pct}%.',

  'note.domainMasking':
    '{count} من المجالات يقل متوسط نطاقها عن أسوأ مؤشر أداء فيها: {domains}. ووفقًا للمنهجية، يظهر الاحتياج الحرج بصرف النظر عن متوسط مجاله — فاقرأ عمود أعلى شدة لمؤشر أداء، لا المتوسط، لهذه المجالات.',
  'note.domainMaskingWorst': '{domain} (الأسوأ: {kpi} عند {severity})',
  'note.geographicMasking':
    '{count} من المحافظات يقل متوسط نطاقها عن أسوأ قرية فيها: {governorates}. اقرأ عمود القرية الأكثر تأثرًا، لا المتوسط، لهذه الصفوف.',

  'chapter.rows.one': 'صف واحد',
  'chapter.rows.two': 'صفان',
  'chapter.rows.many': '{count} صفوف',
  'chapter.charts.one': 'رسم بياني واحد',
  'chapter.charts.two': 'رسمان بيانيان',
  'chapter.charts.many': '{count} رسوم بيانية',
  'chapter.summary': 'ملخص',
  'note.demographicsPending':
    'غير متوفر — لم يتم بعد جمع البيانات الديموغرافية (الجنس / الريف والحضر). سيظهر هذا الرسم البياني عند توفرها.',

  'calc.coverageBasis':
    'احتُسبت على {domains} من المجالات المُقيَّمة، والتي يبلغ مجموع أوزانها المنهجية {weight} من 1.00. ويُعاد تعيير المتوسط المرجّح على تلك المجالات؛ أما المجالات غير المُقيَّمة فلا تُسهم بشيء ولا تُعامل على أنها حققت أداءً جيدًا.',
  'calc.coverageBasisUnavailable':
    'أساس التغطية غير متوفر — لم تُضبط أوزان أولوية للمجالات في هذا الإصدار من المنهجية، لذا تعذّر إنتاج درجة مرجّحة.',
  'calc.needsIndexFormula':
    'مؤشر الاحتياجات = متوسط درجات شدة المجالات المقيسة. ودرجة المجال هي متوسط مجالاته الفرعية المقيسة، والمجال الفرعي متوسط مؤشراته المقيسة، والمؤشر متوسط مؤشرات الأداء المقيسة فيه، ومؤشر الأداء متوسط إجاباته المُقيَّمة. وتُتجاوز المستويات غير المقيسة في كل خطوة، ولا تُحتسب صفرًا أبدًا.',
  'calc.priorityScoreFormula':
    'درجة الأولوية = مجموع ((100 − شدة المجال) × وزن المجال) معادًا تعييرها على مجموع أوزان المجالات المُقيَّمة. وهي مبنية على الأداء، لذا فإن الأقل يعني الأكثر إلحاحًا.',
  'calc.priorityNotCalculable':
    'درجة الأولوية: غير قابلة للاحتساب — لا يوجد تقييم أولوية محفوظ للقرية.',
  'calc.severityBandingRule':
    'الشدة من 0 إلى 100 (الأعلى أسوأ): 70 فأكثر حرج، 50 فأكثر مرتفع، 30 فأكثر متوسط، وأقل من 30 منخفض. والصفر المقيس يُعد منخفضًا؛ أما المؤشر غير المقيس فقيمته فارغة وتُعرض على هيئة «—».',
  'calc.confidenceRule':
    'يكون مستوى الثقة منخفضًا عندما تقل الاستجابات الصالحة عن {minSample} أو تتجاوز نسبة «لا أعرف» {dkThreshold}%؛ وفيما عدا ذلك يكون قياسيًا. ولا يذكر السبب المعروض إلا الشرط الذي تحقق فعليًا.',
  'calc.equityRule':
    'يُفعَّل مؤشر الإنصاف عندما يبلغ تباين الشدة (الأعلى − الأدنى) بين مجموعات أحد الأبعاد {spread} نقطة فأكثر، وتكون كل مجموعة مقارَنة قد بلغت {minGroup} استجابة على الأقل. وحين لا يستوفي أي بعد الحد الأدنى للمجموعة يكون المؤشر غير مُفعَّل ويوضّح السبب أن حجم العينة كان صغيرًا — وهذا ليس دليلاً على انتفاء عدم الإنصاف.',

  'report.RPT01': 'تقرير الاستبيان الفردي',
  'report.RPT02': 'التقرير الجماعي / لوحة المعلومات',
  'report.RPT03': 'تقرير الأولويات العليا',
  'report.RPT04': 'الاحتياجات حسب المجال',
  'report.RPT05': 'الاحتياجات حسب المحافظة',
  'report.RPT06': 'التصفية حسب المنطقة/المحافظة',
  'report.RPT07': 'الاحتياجات حسب الجنس',
  'report.RPT08': 'نتائج مؤشرات الأداء',
  'report.RPT09': 'ترتيب الأولويات',
  'report.RPT10': 'تقرير جودة البيانات',
  'report.RPT11': 'عرض الدراسات السابقة',
  'report.RPT12': 'حالة مشاركة التقارير',
  'report.RPT13': 'الملخص التنفيذي',
  'report.RPT14': 'تقرير القرية',
  'report.RPT15': 'تقرير الاستبيان ولوحة المعلومات',
  'report.RPT16': 'تقرير الأدلة والدرجات المجمّع',
  'report.RPT17': 'التقرير المبني على مستندات الأدلة',

  'report.title.village': 'تقرير القرية — {village}',
  'report.title.scoped': '{report} — {scope}',

  'label.value': 'القيمة',
  'label.field': 'الحقل',
  'label.count': 'العدد',
  'label.percentage': 'النسبة المئوية',
  'label.severityScore': 'درجة الشدة',
  'label.priorityScore': 'درجة الأولوية',
  'label.priorityStatus': 'حالة الأولوية',
  'label.confidence': 'مستوى الثقة',
  'label.domain': 'المجال',
  'label.subDomain': 'المجال الفرعي',
  'label.village': 'القرية',
  'label.governorate': 'المحافظة',
  'label.region': 'المنطقة',
  'label.center': 'المركز',
  'label.need': 'الاحتياج',
  'label.responses': 'الاستجابات',
  'label.affectedPopulation': 'السكان المتأثرون',
  'label.notAvailable': 'غير متوفر',
  'label.item': 'البند',
  'label.detail': 'التفاصيل',
  'label.summary': 'الملخص',
  'label.metric': 'المؤشر',
  'label.difference': 'الفرق',
  'label.viewDetail': 'عرض التفاصيل',
  'sheet.summary': 'الملخص',
  'label.backToSummary': 'العودة إلى الملخص',
  'label.open': 'فتح',
  'label.backToContents': 'العودة إلى المحتويات',
  'label.contents': 'المحتويات',
  'label.contentsHint': 'انقر على أي مربع لفتح ذلك القسم. ويتضمن كل قسم رابطًا للعودة إلى هذه الصفحة.',
};

export const MESSAGES: Record<AppLocale, Record<MessageKey, string>> = { en, ar };
