-- AI summaries in the viewer's language.
--
-- Until now every AI summary was generated in English regardless of the app
-- locale, and Arabic depended on per-string, best-effort translation at render
-- time that silently fell back to English. Summaries are now generated in the
-- requesting user's locale, recorded here, and a viewer in the other language
-- gets a whole-summary translation persisted once in localized_outputs.
--
-- Every existing row was generated by the English-only prompts, so 'en' is the
-- truthful backfill, not just a default. localized_outputs starts empty: the
-- first view in the other language fills it.
--
-- Columns only — no new table, so no RLS policy or cnap_backup coverage change.

ALTER TABLE "ai_priority_summaries"
  ADD COLUMN "output_locale" VARCHAR(5) NOT NULL DEFAULT 'en',
  ADD COLUMN "localized_outputs" JSONB;

ALTER TABLE "evidence_document_summaries"
  ADD COLUMN "output_locale" VARCHAR(5) NOT NULL DEFAULT 'en',
  ADD COLUMN "localized_outputs" JSONB;

ALTER TABLE "combined_report_summaries"
  ADD COLUMN "output_locale" VARCHAR(5) NOT NULL DEFAULT 'en',
  ADD COLUMN "localized_outputs" JSONB;
