-- DropForeignKey
ALTER TABLE "initiatives" DROP CONSTRAINT "initiatives_org_id_fkey";

-- DropForeignKey
ALTER TABLE "need_analytical_status_events" DROP CONSTRAINT "need_analytical_status_events_need_id_fkey";

-- DropForeignKey
ALTER TABLE "need_initiatives" DROP CONSTRAINT "need_initiatives_initiative_id_fkey";

-- DropForeignKey
ALTER TABLE "need_initiatives" DROP CONSTRAINT "need_initiatives_need_id_fkey";

-- DropIndex
--
-- These two are hand-written raw-SQL indexes (GIN/trigram, not expressible
-- via Prisma's @@index) that `prisma migrate dev`'s diff doesn't know about,
-- so it always proposes dropping them on any migration touching this schema.
-- Recreated immediately below rather than actually removed — see the
-- matching CREATE INDEX statements' comments for why each exists.
DROP INDEX "needs_themes_idx";

-- DropIndex
DROP INDEX "system_logs_message_trgm_idx";

-- AC 6 filters and groups needs by theme, and the recurrence factor counts how
-- many needs share one. Both are array-containment queries, which is what GIN
-- indexes exist for. (Originally created in
-- 20260827100000_fr003_priority_scoring; recreated here because this
-- migration's autogenerated diff dropped it — see the DropIndex comment.)
CREATE INDEX "needs_themes_idx" ON "needs" USING GIN ("themes");

-- Free-text search over the message body. Not a Prisma-managed index (no
-- @@index equivalent for GIN/trigram) — kept here deliberately so the search
-- box stays usable as the table grows. (Originally created in
-- 20260808090000_add_system_logs; recreated here for the same reason as
-- needs_themes_idx above.)
CREATE INDEX "system_logs_message_trgm_idx" ON "system_logs" USING GIN ("message" gin_trgm_ops);

-- AlterTable
ALTER TABLE "methodology_config_history" ALTER COLUMN "ai_classification_settings" DROP DEFAULT,
ALTER COLUMN "ai_summary_settings" DROP DEFAULT,
ALTER COLUMN "priority_factor_scales" DROP DEFAULT;

-- AlterTable
ALTER TABLE "methodology_configs" ADD COLUMN     "effective_date" TIMESTAMPTZ(6),
ALTER COLUMN "ai_classification_settings" DROP DEFAULT,
ALTER COLUMN "ai_summary_settings" DROP DEFAULT,
ALTER COLUMN "priority_factor_scales" DROP DEFAULT;

-- `need_statement_summaries.verification_warnings` and `needs.themes` used to
-- have a DROP DEFAULT here — this migration's autogenerated diff wrongly
-- proposed dropping both columns' `DEFAULT '{}'`, because schema.prisma never
-- declared `@default([])` for either field even though the live database
-- (and real application behavior — see prisma/seed-demo.ts, which never sets
-- either field explicitly) already depended on that default existing.
-- Removing it broke seeding with a real NOT NULL constraint violation
-- (`prisma/seed-demo.ts:105`, `tx.need.create()`). Fixed by adding
-- `@default([])` to both fields in schema.prisma instead, so this migration
-- no longer touches either column's default at all.

-- AddForeignKey
ALTER TABLE "need_analytical_status_events" ADD CONSTRAINT "need_analytical_status_events_need_id_fkey" FOREIGN KEY ("need_id") REFERENCES "needs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organisations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "need_initiatives" ADD CONSTRAINT "need_initiatives_need_id_fkey" FOREIGN KEY ("need_id") REFERENCES "needs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "need_initiatives" ADD CONSTRAINT "need_initiatives_initiative_id_fkey" FOREIGN KEY ("initiative_id") REFERENCES "initiatives"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "backup_runs_kind_status_started_idx" RENAME TO "backup_runs_kind_status_started_at_idx";
