import { describe, expect, it, beforeEach, vi } from "vitest";
import { BadRequestException } from "@nestjs/common";
import { orgContext } from "../../tenancy/org-context";
import { EvidenceDocumentsService } from "./evidence-documents.service";

describe("EvidenceDocumentsService", () => {
  let service: EvidenceDocumentsService;
  let mockTenant: Record<string, unknown>;
  let mockStorage: Record<string, unknown>;
  let mockAudit: Record<string, unknown>;

  beforeEach(() => {
    mockTenant = {
      runInOrgContext: vi.fn((fn) => fn(mockTenant)),
      evidenceDocument: {
        create: vi.fn(),
        findMany: vi.fn(),
        findFirst: vi.fn(),
        update: vi.fn(),
        delete: vi.fn(),
      },
      evidenceDocumentChunk: {
        createMany: vi.fn(),
      },
      combinedReportSummary: {
        updateMany: vi.fn(),
      },
    };

    mockStorage = {
      save: vi.fn().mockResolvedValue("mock-storage-key.pdf"),
    };

    mockAudit = {
      record: vi.fn().mockResolvedValue(undefined),
    };

    service = new EvidenceDocumentsService(
      mockTenant as any,
      mockStorage as any,
      mockAudit as any,
    );
  });

  function _withContext<T>(fn: () => Promise<T>): Promise<T> {
    return orgContext.run(
      { requestId: "test-req", orgId: "org-1", actorId: "actor-1", role: "ngo_research_officer" },
      fn,
    );
  }

  describe("parseDocumentText", () => {
    it("should parse text from .txt files successfully", async () => {
      const buffer = Buffer.from("Sample text content from field assessment.");
      const result = await service.parseDocumentText("report.txt", buffer);
      expect(result.text).toBe("Sample text content from field assessment.");
      expect(result.chunkCount).toBe(1);
    });

    it("should parse text from .csv files successfully", async () => {
      const buffer = Buffer.from("Header1,Header2\nValue1,Value2");
      const result = await service.parseDocumentText("data.csv", buffer);
      expect(result.text).toContain("Value1,Value2");
    });

    it("should strip a UTF-8 BOM from .csv exports", async () => {
      const buffer = Buffer.from("﻿Header1,Header2\nValue1,Value2");
      const result = await service.parseDocumentText("bom.csv", buffer);
      expect(result.text.startsWith("Header1")).toBe(true);
    });

    it("should reject scanned/image-only PDFs with unsupported error message", async () => {
      const emptyPdfBuffer = Buffer.from("%PDF-1.4 empty pdf without text objects");
      await expect(service.parseDocumentText("scanned.pdf", emptyPdfBuffer)).rejects.toThrow(
        BadRequestException,
      );
    });

    it("should reject unsupported file extensions", async () => {
      const exeBuffer = Buffer.from("executable binary content");
      await expect(service.parseDocumentText("file.exe", exeBuffer)).rejects.toThrow(
        BadRequestException,
      );
    });

    // Regression guard: the previous implementation regex-scanned the raw bytes
    // and so returned nothing for any PDF whose content streams were
    // FlateDecode-compressed — i.e. virtually every real PDF. A PDF built here
    // and read back proves the text layer is actually decoded.
    it("should extract the text layer from a real PDF", async () => {
      const { renderReportPdf } = await import("../reports/pdf-builder");
      const pdf = renderReportPdf({
        title: "Field Visit Evidence Report",
        headerBand: [{ label: "Reference", value: "EVD-WATER-001" }],
        sections: [
          {
            kind: "note",
            heading: "Observation",
            text: "Borehole yield declined during the dry season.",
          },
        ],
        audit: [{ label: "Generated By", value: "Field Officer" }],
      });

      const result = await service.parseDocumentText("evidence.pdf", pdf);
      expect(result.text).toContain("Field Visit Evidence Report");
      expect(result.text).toContain("EVD-WATER-001");
      expect(result.text).toContain("Borehole yield declined");
    });

    /** BadRequestException carries the human-readable text in its payload. */
    async function rejectionPayload(promise: Promise<unknown>) {
      try {
        await promise;
        throw new Error("expected the call to reject");
      } catch (err: any) {
        return err?.response?.error ?? err?.error;
      }
    }

    it("should explain that images carry no text layer", async () => {
      const png = Buffer.from("89504e470d0a1a0a", "hex");
      const payload = await rejectionPayload(service.parseDocumentText("photo.png", png));
      expect(payload.code).toBe("UNSUPPORTED_FILE_TYPE");
      expect(payload.message).toMatch(/optical character recognition/i);
    });

    it("should tell the user to re-save legacy Office files", async () => {
      const doc = Buffer.from("d0cf11e0a1b11ae1", "hex");
      const payload = await rejectionPayload(service.parseDocumentText("old.doc", doc));
      expect(payload.code).toBe("UNSUPPORTED_FILE_TYPE");
      expect(payload.message).toContain(".docx");
    });

    // The old code reported every failure as "scanned PDF", which sent users
    // looking for a problem in their document instead of the parser.
    it("should report an unreadable PDF as a parse failure, not as scanned", async () => {
      const corrupt = Buffer.from("%PDF-1.4 truncated garbage");
      const payload = await rejectionPayload(service.parseDocumentText("broken.pdf", corrupt));
      expect(payload.code).toBe("PARSING_FAILED");
      expect(payload.message).not.toMatch(/scanned/i);
    });
  });

  describe("splitChunks", () => {
    it("should split long text into ordered chunks", () => {
      const longText = "A".repeat(9000);
      const chunks = service.splitChunks(longText);
      expect(chunks.length).toBe(3);
      expect(chunks[0]!.chunkIndex).toBe(0);
      expect(chunks[1]!.chunkIndex).toBe(1);
      expect(chunks[2]!.chunkIndex).toBe(2);
      expect(chunks[0]!.sectionReference).toContain("Section 1");
    });
  });
});
